CustomerAdministration/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from core import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(TemplateView.as_view(template_name="index.html")), name="index"),
    path("customer/", include("customer.urls")), 
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("login/submit", views.submit_login, name="submit_login")
]

customer/urls.py
from django.urls import path
from .views import CustomerListView, CustomerCreateView, CustomerUpdateView, CustomerDeleteView

app_name = "customer"
urlpatterns = [
    path("list/", CustomerListView.as_view(), name="customer-list"),
    path("", CustomerCreateView.as_view(), name="customer-create"),
    path("<int:id>/", CustomerUpdateView.as_view(), name="customer-update"),
    path("<int:id>/delete", CustomerDeleteView.as_view(), name="customer-delete")
]

core/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    birth_date = models.DateField()
    area_code = models.CharField(max_length=3)
    phone_number = models.CharField(max_length=9)
    country = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_phone_number(self):
        return f"({self.area_code}) {self.phone_number}"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_city(self):
        return f"{self.city} - {self.state}"

    def get_absolute_url(self):
        return reverse("customer:customer-update", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("customer:customer-delete", kwargs={"id": self.id})

    class Meta:
        db_table = "customer"

customer/forms.py
from django import forms
from .models import Customer
from django.db import models


class DateInput(forms.DateInput):
    input_type = "date"


class CustomerForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    birth_date = forms.DateField(widget=DateInput())
    area_code = forms.RegexField(regex=r"^\+?1?[0-9]{2}$",
    error_messages={"invalid": "Invalid Format"})
    phone_number = forms.CharField()
    country = forms.CharField()
    state = forms.CharField()
    city = forms.CharField()

    class Meta:
        model = Customer
        fields = (
            "first_name",
            "last_name",
            "email",
            "birth_date",
            "area_code",
            "phone_number",
            "country",
            "state",
            "city",
        )

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as app_login, logout as app_logout
from django.contrib import messages
# Create your views here.
def login(request):
    return render(request, "login.html")

def submit_login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            app_login(request, user)
            return redirect("index")
        else:
            messages.error(request, "User/pass invalid")
    return redirect("index")


def logout(request):
    app_logout(request)
    return redirect("login")
    

customer/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Customer
from .forms import CustomerForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db.models import Q
# Create your views here.


class CustomerListView(ListView):
    template_name = "customer/customer_list.html"
    model = Customer
    paginate_by = 2
    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            object_list = self.model.objects.filter(
                Q(first_name__icontains=name) | Q(last_name__icontains=name)
                )
        else:
            object_list = self.model.objects.all()
        return object_list 


class CustomerCreateView(CreateView):
    template_name = "customer/customer.html"
    form_class = CustomerForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("customer:customer-list")


class CustomerUpdateView(UpdateView):
    template_name = "customer/customer.html"
    form_class = CustomerForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("customer:customer-list")

    def get_object(self, queryset=None):
        id = self.kwargs.get('id')
        return get_object_or_404(Customer, id=id)


class CustomerDeleteView(DeleteView):
    def get_success_url(self):
        return reverse("customer:customer-list")

    def get_object(self, queryset=None):
        id = self.kwargs.get('id')
        return get_object_or_404(Customer, id=id)

core/templates/index.html
{% extends "model-page.html" %}

{% block content %} <h1>Welcome</h1>{% endblock %}

core/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" >

</head>

<body class="d-flex flex-column">
  <div class="sidenav">
         <div class="login-main-text">
            <h2>CRM<br>Customer relationship management</h2>            
         </div>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <form action="submit", method="POST">{% csrf_token %}
                  <div class="form-group">
                     <label>Usuário</label>
                     <input type="text" class="form-control" placeholder="Usuário" name="username">
                  </div>
                  <div class="form-group">
                     <label>Senha</label>
                     <input type="password" class="form-control" placeholder="Senha" name="password">
                  </div>
                  {% if messages %}
                      {% for message in messages %}
                          <div class="alert alert-danger">{{ message }}</div>
                      {% endfor %}

                  {% endif %}
                  <button type="submit" class="btn btn-black">Login</button>
                 
               </form>
            </div>
         </div>
      </div>
</body>
</html>

core/templates/model-footer.html
<div class="cointainer text-container">
    <center><small>Developed by Lucas Ribeiro</small></center>
</div>

core/templates/model-header.html
<nav class="navbar navbar-expand-sm bg-dark">
    <a href={% url 'index' %} class="navbar-brand">CRM</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a href="{% url 'customer:customer-list' %}" class="nav-link">Customer</a>
        </li>
    </ul>
    <a href="{% url 'logout' %}">Logout</a>

</nav>

core/templates/model-page.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body class="d-flex flex-column">
    <header>
        {% include "model-header.html" %}
    </header>
    <main class="content">
        <div class="container">
            {% block content %} {% endblock %}
        </div>
    </main>
    <footer class="py-4 bg-dark text-white-50">
        {% include "model-footer.html" %}
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>

  <style>
      html, body {
          height: 100%;
      }
      main {
          flex: 1 0 auto;
          margin-top: 5%;
      }
      footer {
          flex-shrink: none;
          margin-top: 2em;
      }
  </style>
</html>

customer/templates/customer/customer.html
{% extends "model-page.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{error|escape}}</strong>
                </div>
            {% endfor %}
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

customer/templates/customer/customer_list.html
{% extends "model-page.html" %}

{% block content %}
    <h2>Customers</h2>
    <a href="{% url 'customer:customer-create' %}">
        <button class="btn btn-success" style="margin-bottom: 5px; float: right;">Add Customer</button>
    </a>
    <form>
        <div class="form-group nb-1">
            <input type="text" name="name" class="form-control" placeholder="Search by name">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>    
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>City</th>
                <th>Phone number</th>
                <th>E-mail</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customer_list %}
            <tr>
                <th><a href="{{customer.get_absolute_url}}">{{customer.get_full_name}}</a></th>
                <th>{{customer.get_full_city}}</th>
                <th>{{customer.get_full_phone_number}}</th>
                <th>{{customer.email}}</th>
                <form action="{{customer.get_delete_url}}" method="post">{% csrf_token %}
                    <th><button class="btn btn-danger">DELETE</button>
                </form>
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <ui class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
        {% else %}
            <li class="page-item disabled"><a href="#" class="page-link">Previous</a></li>
        {% endif %}
        {% for object in page_obj.paginator.page_range %}
            <li class="page-item"><a href="?page={{forloop.counter}}" class="page-link">{{forloop.counter}}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
        {% else %}
            <li class="page-item disabled"><a href="#" class="page-link">Next</a></li>
        {% endif %}
        

    </ui>

{% endblock %}